### ISSUE TITLE
Wrong redirect target after OIDC login

### ISSUE THREAD

**Issue by pkr4711** [perses/perses#3384]
### What did you do?

use keycloak as oidc provider and login to perses with oidc.

OIDC authentication works with a unsightly bug. the final redirect from the logon process points to a wrong url
`https://perses.host.name/perses/api/auth/providers/oidc/keycloak/`
but should be: `https://perses.host.name/perses` (base url of perses)

### What did you expect to see?

after a succesful oidc login a redirect to perses base url: `https://perses.host.name/perses`

### System information

Linux 6.6.103 x64_64

### Perses version

0.52.0

### Perses configuration file

```yaml
api_prefix: /perses
database:
  file:
    extension: json
    folder: /perses
frontend:
  explorer:
    enable: true
  important_dashboards: []
provisioning:
  folders:
  - /etc/perses/provisioning
  interval: 5m
security:
  authentication:
    disable_sign_up: true
    providers:
      enable_native: true
      oidc:
      - client_id: perses-oidc-client
        http:
          tls_config:
            caFile: /ca/ca.crt
        issuer: https://test-keycloak.host.name/realms/test
        name: Keycloak
        redirect_uri: https://perses.host.name/perses/api/auth/providers/oidc/keycloak/callback
        scopes:
        - openid
        - profile
        - email
        - roles
        slug_id: keycloak
  cookie:
    same_site: lax
    secure: false
  enable_auth: true
  readonly: false
```

### Logs

```text
* no log messages from perses container
* in the browser you get: `{"message":"Not Found"}` with HTTP/404
```

**Comment by pkr4711** [comment]
without `api_prefix: /perses` everything works fine. @ibakshay

**Comment by Nexucis** [comment]
We have merged couple of PRs to tackle various issues around `api_prefix`. If you have a way to deploy the image from the main branch `persesdev/perses:main-2025-10-03-6c5d69a8-distroless-debug`, would be great to know if it will solve your issue.

**Comment by pkr4711** [comment]
I'll try it as soon as I find time.

**Comment by Nexucis** [comment]
with v0.53.0-beta.2, this issue is solved.

**Comment by ibakshay** [comment]
This issue is still a bug and not yet resolved. You can check the below screenshots for mroe information. 


## Screenshot 1
<img width="1379" height="339" alt="Image" src="https://github.com/user-attachments/assets/2be654ea-0410-4f6f-ac31-087bf9189a77" />

## Screenshot 2

<img width="1427" height="477" alt="Image" src="https://github.com/user-attachments/assets/051407fa-0f0d-45e2-90ba-9a3ed4f35849" />
