### ISSUE TITLE
Errors on importing migration output

### ISSUE THREAD

**Issue by sjentzschsap** [perses/perses#3472]
### What did you do?

We are migrating a Grafana dashboard over to Perses. The migration (either via `percli migrate -f <ourDashboard>.json --online -o json` or via the UI) works successfully and without errors.

However, when importing, two errors are thrown (by random one of the two, must be random on which issue the perses engine runs into first; when re-triggering the import by chance the other error pops up):
*  `bad request: invalid panel 5: spec.mappings.0.spec.result.value: incomplete value string: ../etc/perses/plugins/StatChart-0.9.0/cue.mod/pkg/github.com/perses/perses/cue/common/mappings.cue:54:10`
* `bad request: invalid panel 14: spec.yAxis.max: cannot reference optional field: min: ../etc/perses/plugins/TimeSeriesChart-0.10.1/schemas/time-series.cue:54:23`

Here is how I could fix the issues (I was guessing actually ...), by adding the respective key/values manually to the migration output before importing:

<img width="1327" height="505" alt="Image" src="https://github.com/user-attachments/assets/c6adc3aa-2bf4-4621-b579-9a0c37b6bcd2" />

<img width="1479" height="562" alt="Image" src="https://github.com/user-attachments/assets/d49fe56c-b94c-4e68-9cd5-a12bb10a4987" />

### What did you expect to see?

I expect Perses to generate migration output that can be successfully imported.

### System information

Linux 6.8.0-1034-azure x86_64

### Perses version

0.52.0

### Perses configuration file

```yaml
security:
    readonly: false
    cookie:
        same_site: lax
        secure: false
    encryption_key: <secret>
    enable_auth: true
    authorization:
        check_latest_update_interval: 30s
    authentication:
        access_token_ttl: 15m
        refresh_token_ttl: 1d
        disable_sign_up: true
        providers:
            enable_native: true
            oidc:
                - slug_id: keycloak
                  name: Keycloak
                  client_id: <secret>
                  client_secret: <secret>
                  redirect_uri: https://<redacted>/api/auth/providers/oidc/keycloak/callback
                  scopes:
                    - openid
                    - profile
                    - email
                    - roles
                  http:
                    timeout: 1m
                    tls_config:
                        caFile: /ca/ca.crt
                        minVersion: TLS12
                        maxVersion: TLS13
                  issuer: https://<redacted>/realms/goon
                  discovery_url: ""
                  disable_pkce: false
    cors:
        enable: false
database:
    file:
        folder: /perses
        extension: json
        case_sensitive: false
provisioning:
    folders:
        - /etc/perses/provisioning
    interval: 5m
frontend:
    disable: false
    explorer:
        enable: true
    information: |-
        <redacted>
plugin:
    path: /etc/perses/plugins
    archive_path: /etc/perses/plugins-archive
    enable_dev: false
```

### Logs

```text
no further logs
```

**Comment by sjentzschsap** [comment]
I hope the provided information is sufficient to fix the two issues.
If we need an actual example Grafana dashboard that causes the issue I would have to check how to create a minimal example, as the dashboard I was using is rather long and complex and I might not be able to share it here.

**Comment by Nexucis** [comment]
@AntoineThebaud I guess that's from the latest change you made about the color migration. Any advices ?

**Comment by Nexucis** [comment]
ah no sorry @AntoineThebaud , this bug has been opened using the v0.52.0. So perhaps this is already fixed with v0.53.0-beta.0.

Any chance you can try with the beta @sjentzschsap ?

**Comment by sjentzschsap** [comment]
Yes, sure, we can try with the latest beta build, if there is a good chance this might be fixed in the meantime. Will report back.

**Comment by sjentzschsap** [comment]
@Nexucis Just tested with [0.53.0-beta.0](https://github.com/perses/perses/releases/tag/v0.53.0-beta.0):

Turns out the following error is still existent:

`bad request: invalid panel 5: spec.mappings.0.spec.result.value: incomplete value string: ../etc/perses/plugins/StatChart-0.10.0/cue.mod/pkg/github.com/perses/perses/cue/common/mappings.cue:54:10`

However, the `invalid panel 14: spec.yAxis.max: cannot reference optional field: min:` error seems to be fixed in the meantime, as I don't see it appearing anymore if I hit import many times (due to the random nature that I discovered in the appearance of the first error it runs into :) ).

**Comment by Nexucis** [comment]
thank you @sjentzschsap for testing it !

@AntoineThebaud over to you :)

**Comment by AntoineThebaud** [comment]
I confirm "max: cannot reference optional field: min" has been fixed, the other one doesn't ring a bell to me, I have to check..

**Comment by ibakshay** [comment]
>However, the invalid panel 14: spec.yAxis.max: cannot reference optional field: min: error seems to be fixed in the meantime, as I don't see it appearing anymore if I hit import many times (due to the random nature that I discovered in the appearance of the first error it runs into :) ).

Yes, I can confirm that this issue is fixed in [this pr](https://github.com/perses/plugins/pull/380) and is released in the latest [0.53.0-beta.0](https://github.com/perses/perses/releases/tag/v0.53.0-beta.0) release.
