### ISSUE TITLE
Value change in DatasourceVariable doesn't update the other variables

### ISSUE THREAD

**Issue by rafi-ruetcse17** [perses/perses#3740]
### What did you do?

I have multiple ListVariables. Kinds are `DatasourceVariable`, `PrometheusLabelValuesVariable` and `PrometheusPromQLVariable` respectively. Other kinds except the `DatasourceVariable` have direct effects on all the panels of the dashboard and other list variables. But when I am changing `DatasourceVariable`, there is effect on the panels or other list variables.

https://github.com/user-attachments/assets/47f4628b-dd54-4bc6-8456-10ad17795321

### What did you expect to see?

Datasource of each panel should be affected by the change on list variable of `DatasourceVariable` kind. Other list variables should be affected also.

### Perses configuration file

```yaml

```

### Logs

```text

```

**Comment by Nexucis** [comment]
I think this bug has been solved. So if you don't use the latest version (v0.52.0) or (v.053.0-beta.4 if you would like to try a less stable version), I would advise to upgrade.

Thanks

**Comment by rafi-ruetcse17** [comment]
> I think this bug has been solved. So if you don't use the latest version (v0.52.0) or (v.053.0-beta.4 if you would like to try a less stable version), I would advise to upgrade.
> 
> Thanks

I will upgrade, try and give an update. Thanks for responding

**Comment by rafi-ruetcse17** [comment]
@Nexucis  I have tried it in the latest version (v0.53.0-beta.4) after upgrading everything. But the issue still exists for `Datasource Variable`. No changes in the panel unlike other type of List variables.

https://github.com/user-attachments/assets/51061339-ab1a-4228-bee7-acf4fb1363a1

**Comment by AntoineThebaud** [comment]
I tried and the issue actually applies to variables exclusively, not panels, see: 

![Image](https://github.com/user-attachments/assets/4798246d-ceb8-4c73-977b-44aebd1971b7)

I don't think this is a plugin (prometheus) specific problem here, it's most likely a broader issue.

**Comment by rafi-ruetcse17** [comment]
@AntoineThebaud not updating other variables is an issue obviously. but I am not getting any change in the panels also. no api calls you see in my screen record. What could be the reason? Would you like to provide me the JSON of the dashboard where you tried?

**Comment by rafi-ruetcse17** [comment]
@AntoineThebaud Hi there

> [@AntoineThebaud](https://github.com/AntoineThebaud) not updating other variables is an issue obviously. but I am not getting any change in the panels also. no api calls you see in my screen record. What could be the reason? Would you like to provide me the JSON of the dashboard where you tried?

**Comment by AntoineThebaud** [comment]
Hmm I'm not able to reproduce what you describe, see here the panel gets well updated after a datasource change https://demo.perses.dev/projects/athebaud/dashboards/test_for__3740

**Comment by rafi-ruetcse17** [comment]
> Hmm I'm not able to reproduce what you describe, see here the panel gets well updated after a datasource change https://demo.perses.dev/projects/athebaud/dashboards/test_for__3740

Thanks for the demo.

**Comment by vikashkumar10sap** [comment]
Hi, we are also facing the same issue - Value change in Promql Variable doesn't update the other variables. I am attaching few exampels below:
### 1. When one provider is selected, Hostname is showing correct values
<img width="808" height="595" alt="Image" src="https://github.com/user-attachments/assets/77ff8bbc-8f6b-4d98-bcf0-94f7952539d1" />

### 2. When multiple Providers are selected it showing all hostnames when hostname is visible, and if we turn off the visibility of hostname its only showing hostname of one of the selected Providers and rest are showing no data


Hostname visible:
<img width="1636" height="1028" alt="Image" src="https://github.com/user-attachments/assets/8cf2cf3d-7729-4e55-99c2-aec8356ff2b6" />


Hostname visibility off:
<img width="1698" height="1060" alt="Image" src="https://github.com/user-attachments/assets/95977e75-d227-418c-9db9-2c1e01907c00" />

### 3. When we select ALL providers, The repeated panels don’t work when we select ALL. However, if we select multiple values (excluding ALL), the data appears only when the hostname filter is visible; otherwise, no data is populated.

<img width="1147" height="537" alt="Image" src="https://github.com/user-attachments/assets/e10bd5bf-db22-4f8d-aea6-8daf00ea681e" />

**Comment by AntoineThebaud** [comment]
@vikashkumar10sap you are reporting a different issue here, not linked to DatasourceVariable + AFAIS variables are correctly updating each other when configured to do so, thus if it's not working for you you likely didnt configure the query part correctly. Please check this.. if you don't spot the issue then please share the dashboard JSON as we can't help you from just the screenshots.

@rafi-ruetcse17 actually everything seem to work fine here, see this sample dashboard https://demo.perses.dev/projects/athebaud/dashboards/test_for__3740. If you are able to reproduce this issue could you share the JSON definition of your dashboard?

**Comment by vikashkumar10sap** [comment]
@AntoineThebaud , please take a look at this related issue - https://github.com/perses/perses/issues/3722

**Comment by AntoineThebaud** [comment]
This other issue is actually not related, panel group repeat is a whole different mechanism.

**Comment by rafi-ruetcse17** [comment]
> [@vikashkumar10sap](https://github.com/vikashkumar10sap) you are reporting a different issue here, not linked to DatasourceVariable + AFAIS variables are correctly updating each other when configured to do so, thus if it's not working for you you likely didnt configure the query part correctly. Please check this.. if you don't spot the issue then please share the dashboard JSON as we can't help you from just the screenshots.
> 
> [@rafi-ruetcse17](https://github.com/rafi-ruetcse17) actually everything seem to work fine here, see this sample dashboard https://demo.perses.dev/projects/athebaud/dashboards/test_for__3740. If you are able to reproduce this issue could you share the JSON definition of your dashboard?

As far as I have seen that panel gets updated after a datasource change. So there is no issue regarding panel update. But other variables are not updating when datasource variable is changed.

**Comment by AntoineThebaud** [comment]
I tried again and I'm not able to reproduce, on my end the variables are updating well when datasource variable is changed. Can you please share the JSON/YAML of a sample dashboard for which  you observe the issue?

**Comment by rafi-ruetcse17** [comment]
@AntoineThebaud Hi. Thank you so much for your effort. I have tested again after seeing your demo dashboard. I was doing something wrong previously. Variables are updating fine. This issue should be closed.
